pkg/cluster/cd/workload/rollout/rollout.go

Signed-off-by: kiloson <4closetool3@gmail.com>

fix: pod status terminating check in rollout

---

pkg/cluster/cd/workload/deployment/deployment.go
pkg/cluster/cd/workload/kservice/kservice.go
pkg/cluster/cd/workload/rollout/rollout.go

Signed-off-by: closetool <c299999999@qq.com>

fix: add resourceVersion = 0 when listing pods

---

pkg/cluster/cd/workload/rollout/rollout.go

This reverts commit ba6e9bc570b377cb487d15a9f4bdac4c018ace1d.

Revert "fix: pod status terminating check in rollout"

---

.pre-commit-config.yaml
core/controller/application/controller.go
core/controller/cluster/controller_basic.go
core/controller/cluster/controller_basic_v2.go
core/controller/cluster/controller_operation.go
core/controller/webhook/models.go
pkg/cluster/tekton/collector/collector_test.go
pkg/cluster/tekton/metrics/resolver_test.go
pkg/event/manager/manager.go
pkg/event/models/event.go
pkg/eventhandler/wlgenerator/wlgenerator.go
pkg/webhook/models/webhook.go

add `application updated`, `cluster updated`, `cluster restart`, `cluster pods rescheduled`.
add extra column to tb_event
```sql
alter table tb_event add column extra varchar(255) not null default '' comment 'extra infos to describe the event'
```

feat: add more events for webhook

---

core/controller/cluster/controller_operation.go
core/controller/cluster/controller_test.go
mock/pkg/cluster/gitrepo/gitrepo_cluster_mock.go
mock/pkg/cluster/manager/manager.go
mock/pkg/templaterelease/manager/manager_mock.go
pkg/cluster/gitrepo/gitrepo_cluster.go
pkg/cluster/gitrepo/gitrepo_cluster_test.go
pkg/templaterelease/dao/dao.go
pkg/templaterelease/manager/manager.go
pkg/templaterelease/manager/manager_test.go

returns directly template chart name and version instead of regular parsing

fix: GetClusterTemplate

---

core/controller/cluster/controller_operation.go
core/controller/cluster/controller_test.go
mock/pkg/cluster/gitrepo/gitrepo_cluster_mock.go
mock/pkg/templaterelease/manager/manager_mock.go
pkg/cluster/gitrepo/gitrepo_cluster.go
pkg/cluster/gitrepo/gitrepo_cluster_test.go
pkg/templaterelease/dao/dao.go
pkg/templaterelease/manager/manager.go
pkg/templaterelease/manager/manager_test.go

Revert "fix: GetClusterTemplate"

---

pkg/application/dao/dao.go
pkg/application/manager/manager_test.go

fix bug: return all apps when filtering by user who does not belong any group

fix: list application sql

---

core/middleware/requestid/requestid.go
mock/pkg/application/gitrepo/gitrepo_applicationv2_mock.go
mock/pkg/cluster/tekton/factory/factory_mock.go
mock/pkg/hook/handler/mock_handler.go
mock/pkg/rbac/role/roles_mock.go
mock/pkg/tag/manager/manager.go
mock/pkg/templateschematag/manager/mock_manager.go
pkg/application/service/service.go
pkg/application/service/service_test.go
pkg/cluster/cd/workload/type.go
pkg/util/time/time.go

refactor code

---

.github/workflows/image.yml
pkg/cluster/gitrepo/gitrepo_cluster.go

* [fix: bug of log pointer address](https://github.com/horizoncd/horizon/pull/93/commits/5262934bba9b449415f083a0ac33d87a2c732529)
* [make ali registry namespace a variable](https://github.com/horizoncd/horizon/pull/93/commits/3d9d35bc74242d4c75a39f495af4c870c7d4d1bb)

fix: bug of log pointer address

---

core/controller/cluster/models_basic_v2.go

bug: miss git subfolder when creating cluster

fix: miss subfolder

---

scripts/install.sh

* install script for kind & minikube

chore: add install scripts

---

.github/PULL_REQUEST_TEMPLATE.md
scripts/install.sh

Fixes #119 
I have:
there's no code change

Promote install script

---

.github/workflows/unit-test.yml
.unit-test.sh
README.md
README_ZH-CN.md

Support code climate
I have:
Has been tested in https://github.com/kilosonc/horizon/actions/runs/4675976847/jobs/8281724905

chore: add code climate coverage statistics

---

scripts/install.sh

add github token to config on installation with script
Fixes #
I have:
The srcipt has been tested locally
```sh
./horizon_install -u
```

fix: add github token to config on installation with script

---

.github/workflows/unit-test.yml

fix: pr could not access secret

---

core/cmd/cmd.go
core/controller/cluster/controller.go
core/controller/cluster/controller_build_deploy.go
core/controller/template/controller_test.go
lib/gitlab/gitlab.go
lib/gitlab/gitlab_test.go
mock/lib/gitlab/mock_gitlab.go
pkg/application/gitrepo/gitrepo_application_test.go
pkg/application/gitrepo/gitrepo_applicationv2.go
pkg/cluster/gitrepo/gitrepo_cluster.go
pkg/cluster/gitrepo/gitrepo_cluster_test.go
pkg/config/gitlab/gitlab.go
pkg/jobs/jobautofree/autofree_test.go
pkg/param/param.go
scripts/install.sh

Fixes https://github.com/horizoncd/horizon/issues/131
* creating an application naned demo when installing.
* add `cn` support for ingress installing.
* print gitlab repo after installing
I have:
Tested locally

chore: improve install bash

---

core/cmd/cmd.go

fix: default Branch in cd

---

CONTRIBUTING.md

Fixes #150
I have:
Check out the rendered results in an [issue](#150)

docs: design contributor documentation

---

core/controller/application/controller.go
core/controller/application/controller_test.go
core/controller/application/models.go
core/controller/application/v2models.go
core/controller/applicationregion/controller_test.go
core/controller/cluster/controller_basic.go
core/controller/cluster/controller_basic_v2.go
core/controller/cluster/controller_operation.go
core/controller/cluster/controller_test.go
core/controller/cluster/models_basic.go
core/controller/cluster/models_basic_v2.go
core/controller/tag/controller.go
core/controller/tag/controller_test.go
core/controller/tag/models.go
pkg/cluster/dao/dao.go
pkg/group/manager/manager_test.go
pkg/region/manager/manager_test.go
pkg/tag/manager/manager.go
pkg/tag/manager/manager_test.go
pkg/tag/models/tag.go

Add tags for application/cluster creating/update/get
I have:
has been tested locally

feat: support tag for application

---

core/controller/cluster/controller_basic.go
core/controller/cluster/controller_basic_v2.go

I have: if there's no tags passed when updating, all tags will be removed

fix: tags disappear when updating cluster

---

core/controller/cluster/controller.go
core/controller/cluster/controller_basic.go
core/controller/cluster/models_basic.go

support collection search under application
I have:
has been tested locally

feat: support collection search under application

---

README.md
README_ZH-CN.md
core/controller/cluster/controller_internal_v2.go
core/controller/cluster/controller_test.go

fix: do not merge branch if diff is empty

---

pkg/jobs/clean/cleaner.go

Fixes: promote rules in cleaner
I have:

fix: rules in cleaner

---

pkg/jobs/clean/cleaner.go
pkg/regioninformers/regioninformers.go

* fixed cleaning time
* client-go using protobuf
I have:

fix: fixed cleaning time

---

pkg/cd/k8sutil.go
pkg/regioninformers/regioninformers.go

fix: offline does not take effect
I have:

fix: offline does not take effect

---

core/cmd/cmd.go
core/controller/cluster/controller_internal_v2.go

fix: impove code

---

core/cmd/cmd.go
pkg/jobs/k8sevent/k8sevent.go
pkg/regioninformers/regioninformers.go

* Informer stucks if there's no such gvr
* add region changes watching for every instance
I have:

fix: informer stuck

---

README.md
README_ZH-CN.md

1. It's better to use relative path to cite document
2. The document link used before is invalid, should add `blob/main` in the middle of the link.

READMD doc use invalid reference doc link

---

core/controller/cloudevent/controller.go
core/controller/cluster/controller_basic.go
core/controller/cluster/controller_basic_v2.go
core/controller/cluster/controller_test.go
pkg/cluster/tekton/collector/collector_s3.go

Fixes
* fix: the inheritance policy of the application buildConfig
* fix: render of instance output failed with duplicated keys
I have:

fix: some bugs

---

core/http/api/v2/cluster/apis_operation.go
pkg/argocd/argocd.go
pkg/argocd/argocd_test.go
pkg/argocd/mock/mock.go
pkg/cluster/metrics/metrics.go
pkg/cluster/metrics/metrics_test.go

Fixes # 500 in resource tree API
I have:

fix: 500 in resource tree API

---

core/controller/cluster/controller.go
core/controller/cluster/controller_basic_v2.go
core/controller/cluster/controller_build_deploy.go
core/controller/cluster/controller_build_deploy_test.go
core/controller/cluster/controller_test.go
core/controller/cluster/models_basic_v2.go
core/controller/cluster/models_basic_v2_test.go
pkg/template/models/template.go

* fix: image url will invalid when git repo could not be fetched
* fix: creating instance fails when template is changed
Fixes #
I have:

Fix: creating instance fails and fix image url

---

core/controller/application/controller.go

fix: webhook event for app update

---

pkg/cd/cd.go
pkg/regioninformers/regioninformers.go

fix: loosen rate limit of clientset in informers

---

pkg/cd/cd.go
pkg/regioninformers/regioninformers.go

add log for stuck in resource tree
I have:

fix: add log for get resource tree

---

pkg/eventhandler/eventhandler.go
pkg/webhook/service/service.go

fix: improve recover log

---

core/cmd/cmd.go
core/controller/badge/controller.go
core/controller/badge/controller_test.go
core/controller/badge/model.go
core/controller/cluster/controller.go
core/controller/cluster/controller_basic.go
core/controller/cluster/controller_basic_test.go
core/controller/cluster/controller_test.go
core/errors/horizonerrors.go
core/http/api/v2/badge/apis.go
core/http/api/v2/badge/routers.go
db/20240105.sql
openapi/v2/restful/badge.yaml
pkg/badge/dao/dao.go
pkg/badge/manager/manager.go
pkg/badge/models/models.go
pkg/param/managerparam/managerparam.go
pkg/server/rpcerror/rpc_error.go
roles.yaml
scopes.yaml

feat: support badge

---

core/http/api/v1/code/apis.go
core/http/api/v2/code/apis.go

fix: response 500 if code project is not found

---

.gitignore
core/controller/cloudevent/controller.go
core/errors/horizonerrors.go
core/middleware/admission/admission.go
go.mod
go.sum
pkg/admission/http.go
pkg/admission/models/models.go
pkg/admission/webhook.go
pkg/admission/webhook_test.go

feat: support for muatating admission webhook

---

core/http/api/v1/idp/apis.go

fix: improve error output

---

pkg/eventhandler/wlgenerator/wlgenerator.go

fix: nil point panic

---

.github/workflows/unit-test.yml

upgrade codeclimate-action to v6.0.0
Fixes #
I have:

upgrade codeclimate-action to v6.0.0
